global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "prometheus-test"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["172.17.0.1:8080"]
        labels:
          application: 'Test Spring Boot Application'
remote_write:
  - url: "http://172.17.0.1:9090/api/v1/write"